### ISSUE TITLE
NPE During startup 1.1.0.RELEASE

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-zookeeper#122]
```
2017-04-13 18:24:10.971+0200 | ERROR |  | main | o.s.b.SpringApplication | Application startup failed
java.lang.NullPointerException: null
        at org.springframework.cloud.zookeeper.serviceregistry.ZookeeperServiceRegistry.register(ZookeeperServiceRegistry.java:82)
        at org.springframework.cloud.zookeeper.serviceregistry.ZookeeperServiceRegistry.register(ZookeeperServiceRegistry.java:43)
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.registerManagement(AbstractAutoServiceRegistration.java:44)
        at org.springframework.cloud.client.discovery.AbstractDiscoveryLifecycle.start(AbstractDiscoveryLifecycle.java:114)
        at org.springframework.cloud.client.discovery.AbstractDiscoveryLifecycle.onApplicationEvent(AbstractDiscoveryLifecycle.java:243)
        at org.springframework.cloud.client.discovery.AbstractDiscoveryLifecycle.onApplicationEvent(AbstractDiscoveryLifecycle.java:42)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:147)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)

```

**Comment by spencergibb** [comment]
From a simple zookeeper discovery enabled app created from http://start.spring.io I am unable to recreate your issue. Can you please share more than just a stack trace? If possible, a project that recreates the problem?

**Comment by dstepanov** [comment]
I'll investigate more next week.

**Comment by dstepanov** [comment]
You need to have `management` enabled.

`ZookeeperAutoServiceRegistration`:
```
	protected ZookeeperRegistration getManagementRegistration() {
		return null;
	}
```
`ZookeeperServiceRegistry`:
```
	public void register(ZookeeperRegistration registration) {
		try {
			getServiceDiscovery().registerService(registration.getServiceInstance());
		} catch (Exception e) {
			rethrowRuntimeException(e);
		}
	}
```

**Comment by spencergibb** [comment]
Thanks, that's what I was missing.

**Comment by damnhandy** [comment]
Is there a work around for this in 1.1.0?  Or is this release hosed at the moment?

**Comment by dstepanov** [comment]
Work around is to disable management:
`management.port: -1`

**Comment by spencergibb** [comment]
You could also extend `ZookeeperServiceRegistry` and register it as a bean named `zookeeperServiceRegistry` and add a null check.

**Comment by damnhandy** [comment]
Hmm, but I'm already setting the management port on all of our services. We've always been running it on another port. Is there something special about `-1`, or is it just looking for a value? Even with a value (not -1), we still get an NPE.

**Comment by dstepanov** [comment]
`-1` is disabling management not randomizing it's port
