### ISSUE TITLE
Application throws NullPointerException if property "spring.application.name" isn't defined

### ISSUE THREAD

**Issue by birkovskyy** [spring-cloud/spring-cloud-zookeeper#152]
In case if "spring.application.name" isn't defined then ZookeeperPropertySourceLocator throws NullPointerException.
```
2017-11-01 12:06:35.040  INFO 13348 --- [           main] o.a.z.ZooKeeper                          : Initiating client connection, connectString=localhost:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@338494fa
2017-11-01 12:06:35.183  INFO 13348 --- [0:0:0:0:1:2181)] o.a.z.ClientCnxn                         : Opening socket connection to server 0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-11-01 12:06:35.185  INFO 13348 --- [0:0:0:0:1:2181)] o.a.z.ClientCnxn                         : Socket connection established to 0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:2181, initiating session
2017-11-01 12:06:35.195  INFO 13348 --- [0:0:0:0:1:2181)] o.a.z.ClientCnxn                         : Session establishment complete on server 0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:2181, sessionid = 0x15f7416a44e001b, negotiated timeout = 40000
2017-11-01 12:06:35.203  INFO 13348 --- [ain-EventThread] o.a.c.f.s.ConnectionStateManager         : State change: CONNECTED

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.0.0.M5)

2017-11-01 12:06:35.571 ERROR 13348 --- [           main] o.s.b.SpringApplication                  : Application startup failed

java.lang.NullPointerException: null
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.locate(ZookeeperPropertySourceLocator.java:94) ~[spring-cloud-zookeeper-config-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:624) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
```
It would be good to have some meaningful description in this case

**Comment by spencergibb** [comment]
Closed via b3b9477
We should use a default (like config client does). Also logs a warning.
