### ISSUE TITLE
add a callback feature with change data

### ISSUE THREAD

**Issue by s332401890** [spring-cloud/spring-cloud-zookeeper#156]
We get spring boot in war. when i integrate spring cloud zookeeper and change the watcher node,the application get some exception .So i think  if RefreshEvent is too heavy ， A custom event is much better for expanding feature 。

**Comment by spencergibb** [comment]
I don't understand. Please expand, provide the error or explain your enhancement more

**Comment by s332401890** [comment]
i have some code , if you are interesting , i will email to you .

**Comment by s332401890** [comment]
2018-01-12 11:19:32.021  INFO 24756 --- [tor-TreeCache-0] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@494c4c68: startup date [Fri Jan 12 11:19:32 GMT+08:00 2018]; root of context hierarchy
2018-01-12 11:19:32.105  INFO 24756 --- [tor-TreeCache-0] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$6e125a75] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-01-12 11:19:32.152  INFO 24756 --- [tor-TreeCache-0] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2018-01-12 11:19:32.152  INFO 24756 --- [tor-TreeCache-0] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.168.0.101:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@352bb3cf
2018-01-12 11:19:32.168  INFO 24756 --- [168.0.101:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.168.0.101/192.168.0.101:2181. Will not attempt to authenticate using SASL (unknown error)
2018-01-12 11:19:53.026  WARN 24756 --- [168.0.101:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.8.jar:3.4.8--1]

2018-01-12 11:19:54.143  INFO 24756 --- [168.0.101:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.168.0.101/192.168.0.101:2181. Will not attempt to authenticate using SASL (unknown error)
2018-01-12 11:19:57.600 ERROR 24756 --- [tor-TreeCache-0] org.apache.curator.ConnectionState       : Connection timed out for connection string (192.168.0.101:2181) and timeout (15000) / elapsed (25448)

org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:200) [curator-client-2.11.1.jar:na]
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:90) [curator-client-2.11.1.jar:na]
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:230) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:219) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:216) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:207) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:40) [curator-framework-2.11.1.jar:na]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.getChildren(ZookeeperPropertySource.java:116) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.findProperties(ZookeeperPropertySource.java:81) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.<init>(ZookeeperPropertySource.java:46) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.create(ZookeeperPropertySourceLocator.java:129) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.locate(ZookeeperPropertySourceLocator.java:107) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:74) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:54) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:35) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.cloud.zookeeper.config.ConfigWatcher.childEvent(ConfigWatcher.java:106) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:730) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:724) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.1.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:723) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:70) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:841) [curator-recipes-2.11.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2018-01-12 11:20:12.810 ERROR 24756 --- [tor-TreeCache-0] org.apache.curator.ConnectionState       : Connection timed out for connection string (192.168.0.101:2181) and timeout (15000) / elapsed (40658)

org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:200) [curator-client-2.11.1.jar:na]
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:90) [curator-client-2.11.1.jar:na]
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:230) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:219) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:216) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:207) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:40) [curator-framework-2.11.1.jar:na]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.getChildren(ZookeeperPropertySource.java:116) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.findProperties(ZookeeperPropertySource.java:81) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.<init>(ZookeeperPropertySource.java:46) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.create(ZookeeperPropertySourceLocator.java:129) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.locate(ZookeeperPropertySourceLocator.java:107) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:74) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:54) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:35) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.cloud.zookeeper.config.ConfigWatcher.childEvent(ConfigWatcher.java:106) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:730) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:724) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.1.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:723) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:70) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:841) [curator-recipes-2.11.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2018-01-12 11:20:14.956  WARN 24756 --- [168.0.101:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.8.jar:3.4.8--1]

2018-01-12 11:20:16.083  INFO 24756 --- [168.0.101:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.168.0.101/192.168.0.101:2181. Will not attempt to authenticate using SASL (unknown error)
2018-01-12 11:20:28.066 ERROR 24756 --- [tor-TreeCache-0] org.apache.curator.ConnectionState       : Connection timed out for connection string (192.168.0.101:2181) and timeout (15000) / elapsed (55914)

org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:200) [curator-client-2.11.1.jar:na]
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:90) [curator-client-2.11.1.jar:na]
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:230) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:219) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109) [curator-client-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:216) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:207) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:40) [curator-framework-2.11.1.jar:na]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.getChildren(ZookeeperPropertySource.java:116) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.findProperties(ZookeeperPropertySource.java:81) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySource.<init>(ZookeeperPropertySource.java:46) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.create(ZookeeperPropertySourceLocator.java:129) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.zookeeper.config.ZookeeperPropertySourceLocator.locate(ZookeeperPropertySourceLocator.java:107) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:74) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:54) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:35) [spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.cloud.zookeeper.config.ConfigWatcher.childEvent(ConfigWatcher.java:106) [spring-cloud-zookeeper-config-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:730) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:724) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.1.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:723) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:70) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:841) [curator-recipes-2.11.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by s332401890** [comment]
version
spring-cloud-dependencies  Dalston.SR4
spring-boot-dependencies  1.5.4.RELEASE

**Comment by s332401890** [comment]
for some mistake, just for suggestion.
i expand for this code.
`import org.apache.curator.framework.recipes.cache.TreeCacheEvent;

/**
 * <when zk update call this interface>
 * @author 332401890
 */

public interface ZKRefreshHandler
{
    /**
     * <ZK refresh callback method>
     * @author s00304153 2018年1月10日
     */
    void handle(TreeCacheEvent event);
}
`

`
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.apache.curator.framework.recipes.cache.TreeCacheEvent;
import org.apache.log4j.Logger;
import org.springframework.beans.BeansException;
import org.springframework.cloud.endpoint.event.RefreshEvent;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.ApplicationListener;

/**
 * <ZK refresh event listener>
 * @author 332401890
 * @since LDC V100R001C00
 */
public class ZKRefreshEventListener implements ApplicationListener<RefreshEvent>, ApplicationContextAware
{
    private static final Logger logger = Logger.getLogger(ZKRefreshEventListener.class);
    
    List<ZKRefreshHandler> handlers = new ArrayList<ZKRefreshHandler>();
     
    @Override
    public void onApplicationEvent(RefreshEvent applicationEvent)
    {
        TreeCacheEvent zkEvent = (TreeCacheEvent)applicationEvent.getEvent();
        
        for (ZKRefreshHandler ZKRefreshHandler : handlers)
        {
            try
            {
                ZKRefreshHandler.handle(zkEvent);
            }
            catch (Exception e)
            {
                logger.error("some error happen when class:"+ZKRefreshHandler.getClass().getName()+" callback");
            }
        }
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException
    {
        Map<String, ZKRefreshHandler> handlersMap = applicationContext.getBeansOfType(ZKRefreshHandler.class);
        if (handlersMap == null)
        {
            return;
        }
        //get all callback
        for (Entry<String, ZKRefreshHandler> entry : handlersMap.entrySet())
        {
            handlers.add(entry.getValue());
        }
    }
}`

**Comment by s332401890** [comment]
when zookeeper change, i have a callback with zookeeper data.

**Comment by s332401890** [comment]
add to version 1.2.X

**Comment by spencergibb** [comment]
We already have an application event. Is that enough?

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by s332401890** [comment]
you are right ,all is nothing. thanks.
