### ISSUE TITLE
Spring Cloud ZooKeeper Discovery Client Does Not Register on ZooKeeper

### ISSUE THREAD

**Issue by xyq000** [spring-cloud/spring-cloud-zookeeper#158]
I have a spring boot application that use spring-cloud-stater-zookeeper-discovery to register the service, but it doesn't work.

1. the application is deployed as a **WAR**.

    <pre>
    @SpringBootConfiguration
    @EnableAutoConfiguration
    @EnableDiscoveryClient
    public class MyApplication extends SpringBootServletInitializer {
    
        @Override
        protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
            return application.sources(MyApplication.class)
                    .properties("spring.cloud.zookeeper.discovery.instance-host=" + getHostName())
                    .web(true);
        }
    }
    </pre>

2. the application has connected to the zookeeper instance. Ping messages to zookeeper can be seen in the application's log and the output of `STAT` command shows a connected zookeeper client.
3. the application does not register watchers to appointed zookeeper path, i.e., `/services`. This can be confirmed by sending `WCHC` command to the zookeeper.

Spring Boot version: 1.5.9

spring-cloud-stater-zookeeper-discovery: 1.2.0.RELEASE

web container: tomcat 8.5.23

**Comment by spencergibb** [comment]
There is a similar problem in consul

**Comment by iurii-dziuban-onpex** [comment]
Any workaround on this?

**Comment by spencergibb** [comment]
Maybe
```
	@EventListener(ApplicationStartedEvent.class)
	public void init(ApplicationStartedEvent event) {
		ConfigurableApplicationContext context = event.getApplicationContext();
		ZookeeperRegistration registration = context.getBean(ZookeeperRegistration.class);
		registration.setPort(9080);
		ZookeeperAutoServiceRegistration serviceRegistration = context.getBean(ZookeeperAutoServiceRegistration.class);
		serviceRegistration.start();
	}
```

**Comment by rodoc81** [comment]
I got the same issue with newer version:

- Spring Boot version: 2.1.0.RELEASE
- spring-cloud-stater-zookeeper-discovery: 2.1.0.M1
- web container: tomcat 8.5.34

I used suggested solution above by @spencergibb .  I'm using properties to set the port so don't need the first part.

`   @Autowired
    private ZookeeperAutoServiceRegistration serviceRegistration;

    @EventListener(ApplicationStartedEvent.class)
    public void init(final ApplicationStartedEvent event) {
        serviceRegistration.start();
    }`

**Comment by xingfudeshi** [comment]
@rodoc81 is this a bug?

**Comment by nicqchen01** [comment]
I have same issues, any one could help on this?

**Comment by nicqchen** [comment]
2019-01-24 07:15:43.006 ERROR 1 --- [nStateManager-0] o.a.c.x.d.details.ServiceDiscoveryImpl   : Could not re-register instances after reconnection

java.lang.IllegalStateException: instance must be started before calling this method
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[curator-client-4.0.1.jar!/:na]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.create(CuratorFrameworkImpl.java:416) ~[curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.internalRegisterService(ServiceDiscoveryImpl.java:236) ~[curator-x-discovery-4.0.1.jar!/:na]
        at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.reRegisterServices(ServiceDiscoveryImpl.java:456) ~[curator-x-discovery-4.0.1.jar!/:na]
        at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.access$100(ServiceDiscoveryImpl.java:58) ~[curator-x-discovery-4.0.1.jar!/:na]
        at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl$1.stateChanged(ServiceDiscoveryImpl.java:78) ~[curator-x-discovery-4.0.1.jar!/:na]
        at org.apache.curator.framework.state.ConnectionStateManager$2.apply(ConnectionStateManager.java:274) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.framework.state.ConnectionStateManager$2.apply(ConnectionStateManager.java:270) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) [curator-client-4.0.1.jar!/:na]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.framework.state.ConnectionStateManager.processEvents(ConnectionStateManager.java:268) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.framework.state.ConnectionStateManager.access$000(ConnectionStateManager.java:44) [curator-framework-4.0.1.jar!/:4.0.1]
        at org.apache.curator.framework.state.ConnectionStateManager$1.call(ConnectionStateManager.java:120) [curator-framework-4.0.1.jar!/:4.0.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]

**Comment by zhuangjinjin** [comment]
it seem that problem was here in EventListenerMethodProcessor, it does't work on SpringContainerClass who annotated @EventListner
`
private static boolean isSpringContainerClass(Class<?> clazz) {
		return (clazz.getName().startsWith("org.springframework.") &&
				!AnnotatedElementUtils.isAnnotated(ClassUtils.getUserClass(clazz), Component.class));
	}

private void processBean(final String beanName, final Class<?> targetType) {
	if (!this.nonAnnotatedClasses.contains(targetType) && !isSpringContainerClass(targetType)) {
	...
	//context#addApplicationListener
	}
}
`

**Comment by zhuangjinjin** [comment]
it seem that problem was here in EventListenerMethodProcessor, it does't work on SpringContainerClass who annotated @EventListner
```java
private static boolean isSpringContainerClass(Class<?> clazz) {
	return (clazz.getName().startsWith("org.springframework.") && !AnnotatedElementUtils.isAnnotated(ClassUtils.getUserClass(clazz), Component.class));
}

private void processBean(final String beanName, final Class<?> targetType) {
	if (!this.nonAnnotatedClasses.contains(targetType) && !isSpringContainerClass(targetType)) {
		...
		//context#addApplicationListener
	}
}
```

**Comment by venkateshzifo** [comment]
Hi,

Any update on this one ? I am facing the same issue when deploy the application as WAR.

**Comment by marcingrzejszczak** [comment]
If there are no comments then there are no updates

**Comment by venkateshzifo** [comment]
Is there any other workaround ?

**Comment by spencergibb** [comment]
Instead of `@EventListener`
```
class MyClass implements ApplicationListener<ApplicationStartedEvent> {
  public void init(final ApplicationStartedEvent event) {
    serviceRegistration.start();
  }
}
```

**Comment by sqnczzl** [comment]
I have the same issuse 

- Spring Boot version: 2.1.4.RELEASE
- spring-cloud-stater-zookeeper-discovery: 2.1.4
- web container: tomcat 8.5.34

**Comment by weihubeats** [comment]
I also encountered a similar problem, mainly caused by the inconsistency of the ZooKeeper server and java client versions. Changing to a consistent version can solve the problem
