### ISSUE TITLE
Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for 

### ISSUE THREAD

**Issue by zhongzunfa** [spring-cloud/spring-cloud-zookeeper#167]
I use a simple example of spring-cloud-zookeeper , but it has an error when I start  the project.

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.web.ServerApplication.main(ServerApplication.java:11) [classes/:na]
Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /services/spring-cloud-zookeeper-server2/fb76236f-bdb3-4fad-ae8e-5be3d8f3c46d

this is the config of my project:
applicaiton.properties:
spring.application.name=spring-cloud-zookeeper-server2
server.port=8822

bootstrap.properties:
spring.cloud.zookeeper.connect-string=localhost:2181

Main:
@SpringBootApplication
@EnableDiscoveryClient
public class ServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(ServerApplication.class, args);
    }
}

spring cloud version: Finchley.RC1
spring boot version: 2.0.1.RELEASE
zookeeper vesion : 3.4.9 or 3.5.3

**Comment by zhongzunfa** [comment]
@spencergibb Can you tell me how to solve it?

**Comment by spencergibb** [comment]
Not at this moment

**Comment by zhongzunfa** [comment]
I am very sorry,   I have a problem with my zookeeper version, using the latest 3.5.3beta of spring-cloud-zookeeper new version .  this bug is not exist.
