### ISSUE TITLE
spring-cloud-zookeeper have error when setting of instance status OUT_OF_SERVICE 

### ISSUE THREAD

**Issue by zhongzunfa** [spring-cloud/spring-cloud-zookeeper#170]
**1.** I create two simple project of spring-cloud-zookeeper 
Below is the basic configuration of my project.

**fiirst :** 
```
spring.cloud.zookeeper.connectString=localhost:2181
spring.application.name=spring-cloud-zookeeper-server
server.port=8811
```

Main Class:

```
@SpringBootApplication
@EnableDiscoveryClient
public class ServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(ServerApplication.class, args);
    }
}
```

Controller critical code  : 

```
List<String> services = client.getServices();  
        for (String service : services){  
            List<org.springframework.cloud.client.ServiceInstance> instances = client.getInstances(service);  
            for (org.springframework.cloud.client.ServiceInstance instance : instances){  
                Collection<ServiceInstance<ZookeeperInstance>> zkInstances = serviceDiscovery.queryForInstances(instance.getServiceId());  
                for (ServiceInstance<ZookeeperInstance> zkInstance : zkInstances) {  
                    ZookeeperServiceRegistry serviceRegistry = new ZookeeperServiceRegistry(serviceDiscovery);  
                    ZookeeperRegistration registration = ServiceInstanceRegistration.builder()  
                            .uriSpec(zkInstance.getUriSpec())  
                            .address(zkInstance.getAddress())  
                            .port(zkInstance.getPort())  
                            .name(zkInstance.getName())  
                            .payload(zkInstance.getPayload())  
                            .build();  
  
                    if(null == zkInstance.getPayload()){  
                        System.out.println("unknow");  
                    }else{  
                        Object status = serviceRegistry.getStatus(registration);  
                        if(zkInstance.getName().equals("spring-cloud-zookeeper-server2")){  
                            serviceRegistry.setStatus(registration, StatusConstants.STATUS_OUT_OF_SERVICE);  
                        }  
                    }  
                }  
            }  
        }  
```

**second:** 

```
spring.cloud.zookeeper.connect-string=localhost:2181
spring.application.name=spring-cloud-zookeeper-server2
server.port=8822
```

the Main class ditto.

2.  the phenomenon:
when execute the code.

`serviceRegistry.setStatus(registration, StatusConstants.STATUS_OUT_OF_SERVICE);`

```
java.lang.Exception: Service not registered: ServiceInstance{name='spring-cloud-zookeeper-server2', id='7fe212c3-2453-4121-9642-afb626c3fb59', address='QJLCPJMMQ4IOW96', port=8822, sslPort=null, payload=ZookeeperInstance{id='application-1', name='spring-cloud-zookeeper-server2', metadata={instance_status=OUT_OF_SERVICE}}, registrationTimeUTC=1526031092312, serviceType=DYNAMIC, uriSpec=org.apache.curator.x.discovery.UriSpec@6c2ac0dc, enabled=true}
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.updateService(ServiceDiscoveryImpl.java:201) ~[curator-x-discovery-4.0.1.jar:na]
	at org.springframework.cloud.zookeeper.serviceregistry.ZookeeperServiceRegistry.setStatus(ZookeeperServiceRegistry.java:110) 
```

3. location

```
 private final ConcurrentMap<String, Entry<T>> services = Maps.newConcurrentMap();
```

the services properties length is always zero of `ServiceDiscoveryImpl` class.

```
public ServiceDiscoveryImpl(CuratorFramework client, String basePath, InstanceSerializer<T> serializer, ServiceInstance<T> thisInstance, boolean watchInstances)
    {
        this.watchInstances = watchInstances;
        this.client = Preconditions.checkNotNull(client, "client cannot be null");
        this.basePath = Preconditions.checkNotNull(basePath, "basePath cannot be null");
        this.serializer = Preconditions.checkNotNull(serializer, "serializer cannot be null");
        if ( thisInstance != null )
        {
            Entry<T> entry = new Entry<T>(thisInstance);
            entry.cache = makeNodeCache(thisInstance);
            services.put(thisInstance.getId(), entry);
        }
    }

    @Override
    public void updateService(final ServiceInstance<T> service) throws Exception
    {
        Entry<T> entry = services.get(service.getId());
        if ( entry == null )
        {
            throw new Exception("Service not registered: " + service);
        }
        synchronized(entry)
        {
            entry.service = service;
            byte[] bytes = serializer.serialize(service);
            String path = pathForInstance(service.getName(), service.getId());
            client.setData().forPath(path, bytes);
        }
    }
```

in addition, I read the  `DefaultServiceDiscoveryCustomizer` class  No pass parameters `ServiceInstance`.

```
public DefaultServiceDiscoveryCustomizer(CuratorFramework curator, ZookeeperDiscoveryProperties properties, InstanceSerializer<ZookeeperInstance> instanceSerializer) {
		this.curator = curator;
		this.properties = properties;
		this.instanceSerializer = instanceSerializer;
	}

	@Override
	public ServiceDiscovery<ZookeeperInstance> customize(ServiceDiscoveryBuilder<ZookeeperInstance> builder) {
		// @formatter:off
		return builder
				.client(this.curator)
				.basePath(this.properties.getRoot())
				.serializer(this.instanceSerializer)
				.build();
		// @formatter:on
	}
```

How to solve this problem?

**Comment by zhongzunfa** [comment]
@spencergibb  Do you have time to help with this?

**Comment by marcingrzejszczak** [comment]
I think that Spencer will reply once he has some time. Can you create a failing test in Zookeeper's codebase to prove your point?

**Comment by zhongzunfa** [comment]
ok, this is my project address.
address : https://github.com/zhongzunfa/spring-cloud-zookeeper-register.git

**Comment by spencergibb** [comment]
Is this still a problem with the latest Finchley.SR2?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
