### ISSUE TITLE
spring-cloud-zookeeper-config refactor issue

### ISSUE THREAD

**Issue by raphsoft** [spring-cloud/spring-cloud-zookeeper#26]
spring-cloud-zookeeper-config/src/main/resources/META-INF/spring.factories still references to 
org.springframework.cloud.zookeeper.config.ZookeeperConfigBootstrapConfiguration but it was refactored to org.springframework.cloud.zookeeper.common.ZookeeperConfigBootstrapConfiguration by marcingrzejszczak  with commit 85a139f60f19aa5fca22d18f7c429cb90c79addc. Applications depending on spring-cloud-zookeeper-all are failing with error "ClassNotFoundException" at runtime. Please provide fast support.
```
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.zookeeper.config.ZookeeperConfigBootstrapConfiguration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.LauncherssLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:284)
        ... 14 more      
```

**Comment by spencergibb** [comment]
@raphsoft you should be good.  I added a test that will catch this kind of stuff in the future.

**Comment by raphsoft** [comment]
@spencergibb thanks!
I still have the same error in my project. do you know when the fixed artifact will be available in http://repo.spring.io/snapshot/?

**Comment by spencergibb** [comment]
It was there when [this build](https://travis-ci.org/spring-cloud/spring-cloud-zookeeper/builds/74942486) completed.  Maybe `mvn -U` to update snapshots.

**Comment by raphsoft** [comment]
got it working without any inconvenient again. thanks once more
