### ISSUE TITLE
Although spring.cloud.config.discovery.enabled=false, CuratorFramework bean is created after boostrap phase.

### ISSUE THREAD

**Issue by yonguk-kim** [spring-cloud/spring-cloud-zookeeper#280]
Although spring.cloud.config.discovery.enabled=false, CuratorFramework bean is created after bootstrap phase with the name of configDataCuratorFramework, so the `spring.cloud.zookeeper.connect-string` value is required for the bootstrap phase.

For this reason, a CuratorFramework bean that is set with the `spring.cloud.zookeeper.connect-string` value obtained from Config Server cannot be created in ZookeeperAutoConfiguration.

If `spring.cloud.config.discovery.enabled=false`, how can I disable the creation of CuratorFramework bean(configDataCuratorFramework)?

I'm using spring-cloud-config-client 3.0.1 and spring-cloud-zookeeper-discovery 3.0.0

**Comment by xvolks** [comment]
When packaged as an executable JAR, this issue (or something close) pops again.
Using SpringBoot 2.6.0-M1 and Spring Cloud 2021.0.0-M1.

The same object is registered twice.
This behavior does not occur when launched from debugger, only when packaged as JAR.

extract of pom.xml
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.0-M1</version>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.5.21</kotlin.version>
        <kotlin.code.style>official</kotlin.code.style>
        <junit.version>4.13.2</junit.version>
        <spring-cloud.version>2021.0.0-M1</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.3</version>
               .....
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.5.21</version>

```

application.yml
```
spring:
  application:
    name: test
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
#    zookeeper:
#      connect-string: localhost:2181
#      discovery:
#        enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: "optional:zookeeper:"
```

Application.kt
```
@SpringBootApplication
@Configuration
@EnableDiscoveryClient
open class Application : WebMvcConfigurer {
    override fun addViewControllers(registry: ViewControllerRegistry?) {
        registry?.addViewController("/")?.setViewName("index.html")
    }

}

fun main(args: Array<String>) {
    println("Hello, World")
    SpringApplication.run(Application::class.java, *args)
}

```


Exception:
```
java.lang.IllegalStateException: Could not register object [org.apache.curator.framework.imps.CuratorFrameworkImpl@3fc79729] under bean name 'configDataCuratorFramework': there is already object [org.apache.curator.framework.imps.CuratorFrameworkImpl@3fc79729] bound
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:124)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:1138)
        at org.springframework.cloud.zookeeper.CuratorFactory.lambda$registerCurator$5(CuratorFactory.java:120)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.DefaultBootstrapContext.close(DefaultBootstrapContext.java:133)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:366)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:298)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1273)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1262)
        at fr.tessi.lab.ApplicationKt.main(Application.kt:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by xvolks** [comment]
After digging deeper I can say that the issue is related to the event `spring.boot.application.environment-prepared` fired twice. So in `CuratorFactory` the close listener is called twice (`registery.addCloseListener(event -> {`.

On my own version of `org.springframework.cloud.zookeeper.CuratorFactory`, I've patched the event listener to call the `registerSingleton` function only once. But this is not a solution.
```
				try {
					Object bean = event.getApplicationContext().getBeanFactory().getBean("configDataCuratorFramework");
					if (bean != curatorFramework) {
						log.warn("Will register bean configDataCuratorFramework with " + curatorFramework, new Throwable("HERE"));
						event.getApplicationContext().getBeanFactory().registerSingleton("configDataCuratorFramework",
								curatorFramework);
					}
					else {
						log.warn("Will NOT register bean configDataCuratorFramework with " + curatorFramework, new Throwable("HERE"));
					}
				}
				catch (NoSuchBeanDefinitionException e) {
					log.warn("configDataCuratorFramework bean not found", e);
					event.getApplicationContext().getBeanFactory().registerSingleton("configDataCuratorFramework",
							curatorFramework);
				}
```

**Comment by xvolks** [comment]
OK, I've figured it out (mostly).
In my application.yml, I have:
```
spring:
  config:
    import: "optional:zookeeper:"
```

This file is in `src/main/resources`, so when the package phase run it bundles this file with the JAR.
Then, at installation time this file is extracted form the JAR to be personalized by the user. 
When the JAR is launched, Springboot for some reason, I do not understand (I know mostly nothing about Springboot), parses both `application.yml` (one by the JAR in the same directory and one inside the JAR).

So if I comment out `import: "optional:zookeeper:"` from one of the YML files, it works as expected. 

I let my  comments here for reference if anybody has the same problem in the future, including myself...
