### ISSUE TITLE
Brixton.M1 ClassNotFoundException: org.apache.curator.framework.recipes.cache.TreeCacheListener

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-zookeeper#36]
When creating an app from http://start.spring.io and choosing Zookeeper Discovery.

```
java.lang.ClassNotFoundException: org.apache.curator.framework.recipes.cache.TreeCacheListener
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_05]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_05]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_05]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_05]
	... 45 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: org/apache/curator/framework/recipes/cache/TreeCacheListener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_05]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_05]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_05]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[na:1.8.0_05]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_05]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[na:1.8.0_05]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_05]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_05]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_05]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_05]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688) ~[na:1.8.0_05]
	at java.lang.Class.getDeclaredMethods(Class.java:1962) ~[na:1.8.0_05]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:606) ~[spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:518) ~[spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:504) ~[spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:325) [spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanType(OnBeanCondition.java:312) [spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:267) [spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:110) [spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45) [spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:673) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:667) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:342) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:980) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at zkdemo.ZkdemoApplication.main(ZkdemoApplication.java:20) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.0.M5.jar:1.3.0.M5]
```

**Comment by spencergibb** [comment]
For some reason maven brings in v2.6.0 of curator-recipes, rather than 2.8.0.

**Comment by spencergibb** [comment]
Also happens with Brixton.BUILD-SNAPSHOT.

Using `mvn dependency:tree` you get
```
org.apache.curator:curator-recipes:jar:2.6.0:compile
```

Not matter what I do to the starters or spring-cloud-zookeeper/pom.xml you always get 2.6.0.

Putting this in the pom.xml of the generated project is the __ONLY__ way I've found to overcome this.
```
<dependency>
    <groupId>org.apache.curator</groupId>
    <artifactId>curator-recipes</artifactId>
    <version>2.8.0</version>
</dependency>
```

/cc @dsyer @wilkinsona any ideas?

**Comment by spencergibb** [comment]
adding -X yields
```
[DEBUG]       org.apache.curator:curator-recipes:jar:2.6.0:compile (version managed from 2.8.0 by org.springframework.cloud:spring-cloud-cluster:1.0.0.BUILD-SNAPSHOT)
[DEBUG]          org.apache.curator:curator-framework:jar:2.8.0:compile (version managed from 2.6.0 by org.springframework.cloud:spring-cloud-zookeeper:1.0.0.BUILD-SNAPSHOT)
```

**Comment by spencergibb** [comment]
And I finally see it, `spring-cloud-cluster` is managing the version :-(
