### ISSUE TITLE
when post endpoint "/refresh", throw this exception: Background exception was not retry-able or retry gave up

### ISSUE THREAD

**Issue by tietang** [spring-cloud/spring-cloud-zookeeper#67]
```
20160322.18:00:48.769 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration [PropertySourceBootstrapConfiguration.java:93] - Located property source: CompositePropertySource [name='zookeeper', propertySources=[ZookeeperTreeCachePropertySource [...]]]
20160322.18:00:48.774 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.boot.SpringApplication [SpringApplication.java:670] - The following profiles are active: dev
20160322.18:00:48.781 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.context.annotation.AnnotationConfigApplicationContext [AbstractApplicationContext.java:578] - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@189535cf: startup date [Tue Mar 22 18:00:48 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@a971ff6
20160322.18:00:48.821 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor [AutowiredAnnotationBeanPostProcessor.java:153] - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
20160322.18:00:48.868 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.boot.SpringApplication [StartupInfoLogger.java:57] - Started application in 1.1 seconds (JVM running for 153.459)
20160322.18:00:48.869 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.context.annotation.AnnotationConfigApplicationContext [AbstractApplicationContext.java:960] - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@189535cf: startup date [Tue Mar 22 18:00:48 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@a971ff6
20160322.18:00:48.874 192.168.10.172 /refresh [XNIO-2 task-6]  INFO org.springframework.context.annotation.AnnotationConfigApplicationContext [AbstractApplicationContext.java:960] - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@a971ff6: startup date [Tue Mar 22 18:00:47 CST 2016]; root of context hierarchy
20160322.18:00:48.964   [XNIO-2 task-6-EventThread] ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl [CuratorFrameworkImpl.java:561] - Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:373)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.doRefreshData(TreeCache.java:261)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.refresh(TreeCache.java:226)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.wasCreated(TreeCache.java:280)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.processResult(TreeCache.java:411)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:743)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:520)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
20160322.18:00:48.976   [XNIO-2 task-6-EventThread] ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl [CuratorFrameworkImpl.java:561] - Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:373)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.doRefreshData(TreeCache.java:261)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.refresh(TreeCache.java:226)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.wasCreated(TreeCache.java:280)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.processResult(TreeCache.java:411)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:743)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:520)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
```

**Comment by marcingrzejszczak** [comment]
Hi! Do you have a sample project that we can check?

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by tietang** [comment]
I have fixed it. The new spring-cloud-zookeeper version take a new refreshable feature（spring.cloud.zookeeper.config.watcher.enabled）, and my project have a refreshable zk node data feture, them have conflict. tks.
